name: Android CI

on:
  push:
    branches: [ master, develop ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build debug app
      run: ./gradlew assembleDebug
    - name: Upload apk
      uses: actions/upload-artifact@v2
      with:
        name: app-debug
        path: app/build/outputs/apk/debug/app-debug.apk

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Lint
      run: ./gradlew lint
    - name: Unit tests
      run: ./gradlew testDebugUnitTest
    - name: Upload reports
      uses: actions/upload-artifact@v2
      with:
        name: test-reports
        path: app/build/reports
      if: always()